version: "0.2"
ignorePaths: []
allowCompoundWords: false
flagWords:
  - workzone
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words: []
ignoreWords: []
import: []
enabled: true
